# Define a common environment block for reuse
x-common-env: &common-env
  # LLM Provider Configuration
  LLM_PROVIDER: ${LLM_PROVIDER}
  LLM_MODEL: ${LLM_MODEL}
  # API Keys
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}

services:
  gateway:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/gateway
    environment:
      <<: *common-env # Inherit common environment variables
      # Gateway-specific environment variables
      REDIS_URL: redis://redis:6379/0
      NATS_URL: nats://nats:4222
      QDRANT_URL: http://qdrant:6333
      GATEWAY_PORT: ${GATEWAY_PORT}
      POLICY_URL: http://policy:8000
      TICKET_URL: http://ticket:8000
      ACTION_URL: http://action:8000
      ESCALATION_URL: http://escalation:8000
    ports:
      - "${GATEWAY_PORT:-8000}:8000"
    depends_on:
      - policy
      - ticket
      - action
      - escalation
    networks:
      - campus-net

  ingest:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/ingest
    environment:
      <<: *common-env
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - campus-net

  policy:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/policy
    environment:
      <<: *common-env
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - campus-net

  action:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/action
    environment: *common-env
    networks:
      - campus-net

  ticket:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/ticket
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=host.docker.internal # Use this hostname to connect to the host machine
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - campus-net

  escalation:
    build:
      context: .
      dockerfile: services/bases/Dockerfile
      args:
        SERVICE_DIR: services/escalation
    environment: *common-env
    networks:
      - campus-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - campus-net

  nats:
    image: nats:2-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
    networks:
      - campus-net

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
    networks:
      - campus-net

networks:
  campus-net:
    driver: bridge
