version: "3.9"

services:
  gateway:
    build:
      context: ./services/gateway
      dockerfile: ../bases/Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
      - NATS_URL=${NATS_URL}
      - QDRANT_URL=${QDRANT_URL}
      - GATEWAY_PORT=${GATEWAY_PORT}
    ports:
      - ${GATEWAY_PORT}:8000
    depends_on:
      - redis
  ingest:
    build:
      context: ./services/ingest
      dockerfile: ../bases/Dockerfile
    environment:
      - NATS_URL=${NATS_URL}
    depends_on:
      - nats

  router:
    build:
      context: ./services/router
      dockerfile: ../bases/Dockerfile
    environment:
      - NATS_URL=${NATS_URL}
    depends_on:
      - nats
  policy:
    build:
      context: ./services/policy
      dockerfile: ../bases/Dockerfile
    environment:
      - QDRANT_URL=${QDRANT_URL}
    depends_on:
      - qdrant
  answer:
    build:
      context: ./services/answer
      dockerfile: ../bases/Dockerfile
  action:
    build:
      context: ./services/action
      dockerfile: ../bases/Dockerfile
  ticket:
    build:
      context: ./services/ticket
      dockerfile: ../bases/Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

  escalation:
    build:
      context: ./services/escalation
      dockerfile: ../bases/Dockerfile

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nats:
    image: nats:2-alpine
    command: ["-js"]
    ports:
      - "4222:4222"

  qdrant:
    image: qdrant/qdrant:v1.9.2 
    ports:
      - "6333:6333"
